### ISSUE TITLE
OpenRSC development should be marked as Complete rather than Active

### ISSUE THREAD

**Issue by dginovker** [opengaming/osgameclones#2681]
They be cool like that

**Comment by cxong** [comment]
This issue hasn't come up much in the past, but I prefer active over complete, since it shows that the game project is active and there's a good chance for contributions to be actioned. See the definition in the schema here:

https://github.com/opengaming/osgameclones/blob/master/schema/games.yaml#L37

> Complete: development stopped but game is complete

So "complete" should only be used if the development has stopped. However I can see this isn't great for games that are both feature-complete and actively maintained. So I guess we can show this in the `info` field.

FWIW the development/status fields were defined here https://github.com/opengaming/osgameclones/issues/360 but as you can see the PR is massive and contains lots of other changes, so there wasn't a thorough discussion on every issue so there are inconsistencies.
