### ISSUE TITLE
Make repo and license fields mandatory

### ISSUE THREAD

**Issue by nikuda** [opengaming/osgameclones#376]
A game is not really open source without those two :)

**Comment by wonea** [comment]
I disagree about the license field. Many repositories do not have a specified license, this is a valid state.

More on this;
http://programmers.stackexchange.com/questions/276144/using-unlicensed-code

**Comment by nikuda** [comment]
>Code without an explicit license is protected by copyright and is by default All Rights Reserved. 

No license implies copyright though, from the link you shared.  It's certainly a valid state, but why should osgc list questionable code, or implied proprietary code?

**Comment by cxong** [comment]
If it does not have a license, you can fill it in with "none" or "all rights reserved"

**Comment by piranha** [comment]
`none` sounds ok, since in this case it's easier to search/fix/notify someone about it. :)

**Comment by nikuda** [comment]
People might take `none` to mean public domain though? `unlicensed` is probably a better term and it will be clearer to understand when it shows up in the tags on the site.

>If you find software that doesn’t have a license, that generally means you have no permission from the creators of the software to use, modify, or share the software. Although a code host such as GitHub may allow you to view and fork the code, this does not imply that you are permitted to use, modify, or share the software for any purpose.
>
>Your options:
>
>**Ask the maintainers nicely to add a license**. Unless the software includes strong indications to the contrary, lack of a license is probably an oversight. If the software is hosted on a site like GitHub, open an issue requesting a license and include a link to this site, or if you’re bold and it’s fairly obvious what license is most appropriate, open a pull request to add a license.
>
>**Don’t use the software**. Find or create an alternative that is under an open source license.
>
>**Negotiate a private license**. Bring your lawyer.

http://choosealicense.com/no-license/

**Comment by piranha** [comment]
Let's call it `no-license` then. :-)

**Comment by JayFoxRox** [comment]
I'm also aware of source code leaks into the public part of the internet (even here on github).

Tony Hawk's Underground for example has it's full code leaked (here on GitHub) for example and also an old version of Acura Soccer had the full code leaked on a magazine coverdisc by accident. I also know of a dancing game where the code was accidentally leaked.

*If* those are listed (should they?) I'd also think there should be some kind of hint that these *probably* shouldn't be public (something like `leak` or `illegal`). It just wouldn't be a good idea to call these `no-license`, because while some releases might be intentional, but poorly executed, others would be unintentional or even done in spite, but rather well executed (as the code got out which was the leakers wish).

**Comment by cxong** [comment]
Illegal code won't be added at all. I think we denied a bunch of PRs for Xash3D for the same reason.

**Comment by cxong** [comment]
About the repo field, my PR doesn't make that required. I've found a few cases that make it problematic:

- Some projects don't have a VCS, they have a page where you can download binaries, and sometimes the source code, or it's all included in the archive. There could be different archives depending on platform and version. Therefore it isn't appropriate to link to one of them.
- I've had to update a lot of sourceforge repo links, since over the years the URL has changed, or they've for example switched from CVS to SVN which changes the URL.

So in some cases the repo and url pages will be the same. I didn't feel it necessary to make repo required. It might be better to make sure at least one of url or repo are present. Thoughts?
