### ISSUE TITLE
New category for loosely related games

### ISSUE THREAD

**Issue by Hiradur** [opengaming/osgameclones#398]
Right now osgameclones focuses on engine reimplementations, remakes and clones of existing games. There are some FOSS games which don't really fit into these categories but may still be interesting to players of a certain game.

Examples:
- [Planeshift](http://www.planeshift.it/) is an MMORPG not based on any other game AFAIK. Yet it may be of interest to players of World of Warcraft.
- [The Cursed](http://www.indiedb.com/games/the-cursed) is an RTS game listing Starcraft and Command and Conquer as an inspiration. Even though it's not really a clone of any of these games it may be of interest to players of these games.

Related:
I like the search interface of osgameclones a lot. Maybe osgameclones could even be turned into a database of all existing FOSS games, even if they are not based on any existing game (e.g. [Red Eclipse](http://redeclipse.net/))

**Comment by piranha** [comment]
I've been thinking a bit about converting osgameclones to being just general catalogue of open source games. But then of course project name should change, and some committee of people around the project should be collected - you can see I'm not replying as fast as I should (and would like). 

Right now there are two of us maintaining the project (and I like that @wonea is here, sometimes I'm drowning in real life and osgc is a bit too much). Do you think we can assemble committee which will carry the project forward given much bigger scope? 

Also, in case we're doing general catalogue, a lot of questions arises. Descriptions, showing less on an index page/first load - it's 855 kb already, how much it will be with more games? Criterions - there should be some bar, because including every one of small projects is going to be too painful. Also, speaking of data volume, is current system enough to handle bigger amount of data/changes? :)

All in all, a lot of questions! I'm pretty sure they all can be answered, and the main one, as always, is with people - are there enough of us to support a bigger project?

Any volunteers for helping to maintain a project like this? :) Also, for carrying it forward, since it I really am distracted by real life enough to be more of a drag rather than carry. :)

**Comment by tukkek** [comment]
I agree that currently this project is very clearly only for "game clones" (and remakes) as the name implies. I like the idea of it becoming a general listing of open source games but really, aren't there many websites for that already? A few examples:

* Libre game wiki http://libregamewiki.org/
* Games on GitHub https://github.com/leereilly/games
* Wikipedia's list of open-source video games https://en.wikipedia.org/wiki/List_of_open-source_video_games

Unless there's a very good reason to change the list from what it is today to "another general FOSS game list" I don't think it is worth the effort as currently it has a well-defined purpose and does it very well, with a big list of games that aren't easy to find anywhere else. I don't like the idea of adding "similar games" like @Hiradur suggests because then any game could be brought up on the list - for example any MMORPG is "similar' to World or Warcraft and any RTS is "similar" to Starcraft, etc etc. If would be like opening up a Pandora box and as @piranha says there aren't many people taking care of the project currently to start cataloging any and all FOSS game out there.

**Comment by Hiradur** [comment]
What I like about osgameclones is its search ability. Not only can you search for game titles but also for programming languages, frameworks etc. to find projects you are interested in. None of the other lists has this feature. I agree however that the purpose of osgameclones.com is well defined right now and nicely fills out a niche that is otherwise not filled.

Since turning osgameclones into a general list of open source games would require a lot more contributors I'd say we leave this issue open and see how much feedback it receives. However, if it happens there should be an option to limit the scope to game clones.

**Comment by tukkek** [comment]
> there should be an option to limit the scope to game clones

This is the main problem here, I doubt anyone will come up with any definition that is reasonable and also doesn't allow for the entry of just about any open-source game to the list because it is "somewhat somehow" similar to that X or Y game. There are thousands and thousands of games released, a dev's project is bound to be "similar" to any of them. 

My own Javelin project (check it out on GH if you like roguelikes and TBS :D) is quite similar to a lot of games, drawing direct inspiration from Heroes of Might and Magic, Jagged Alliance and so many other titles that I love. I would be very tempted to add it to the list because it means more publicity for my FOSS game but I wont because it is not a remake or clone. If we start making exceptions we'll see all kinds of developers and "loosely similar" games being requested into the list. It will be like a flood gate which we cannot close or a Pandora box. I say we leave that to other listing and indexes.

> I'd say we leave this issue open and see how much feedback it receives

I am also against this. The issue tracker is not a lingering place for issues to stay open in a limbo. It is not a dev wiki or forum but a catalog of actionable changes to the project, which should either be worked on or discarded. A relevant issue can be reopened later on or a new issue can be created if the situation ever changes. If this doesn't receive any more relevant feedback in a month or so and no else takes offense to my decision I'll probably be closing this. There are already close to 30 open issues to be worked on at the moment and our goal should be to bring this number down, not keep open issues lingering for the benefit of the doubt that they maybe, someday could be useful.

**Comment by cxong** [comment]
My 2c is that we haven't been receiving a flood of games addition requests so for now we don't need to worry so much about this. For clearly related games we can use the recently-added `similar` (#406). Let's revisit if this ever becomes a problem again.
