### ISSUE TITLE
Combine remakes/clones lists, add more types

### ISSUE THREAD

**Issue by cxong** [opengaming/osgameclones#583]
We currently show separate lists for remakes and clones. For example this is what Spear of Destiny looks like:

![image](https://user-images.githubusercontent.com/1083215/41891907-99261262-7959-11e8-8f0a-82c761f0a91c.png)

Let's combine them like this:

![image](https://user-images.githubusercontent.com/1083215/41892001-f6f49dd2-7959-11e8-946f-b5fbcd860581.png)

Why? It looks neater, matches closer with how users might use the site (look for open source projects related to a game), and allows us to add more types of projects - tools #71, ports #533, patches (e.g. #580)

How to present these? I suggest turning it into a separate tag, like this:

![image](https://user-images.githubusercontent.com/1083215/41892194-92d2418c-795a-11e8-9410-a7de8538b85d.png)

**Comment by tzizi** [comment]
To add support for more types of projects, I'm guessing a `type` attribute would be needed in the games folder.

Although it would require changing everything (possibly via a script?), this is the way I'd invision it:

```
    type: remake
    originals: [Bomberman]
```

Instead of the current:

```
    remakes: [Bomberman]
```

So then for tools or patches, it would simply be a matter of replacing the `type` attribute.
