### ISSUE TITLE
Sort by added/updated

### ISSUE THREAD

**Issue by SamHasler** [opengaming/osgameclones#93]
Could it be possible to sort the list by added/updated date so that when someone returns to the page they can see what was added since they last visited.

**Comment by cxong** [comment]
I've been thinking about this issue, and I think it might be best to start looking into a web framework like React or Vue. We currently do our tags/filters using basic javascript; it works but is not the most maintainable. With a framework this kind of stuff can be added easily. Thoughts?

**Comment by piranha** [comment]
With framework like that you'll either have only client-side rendering or a need for a much more elaborate setup with server-side rendering, instead of simply serving an HTML file like it works right now.

Maybe it's better to look instead at some frameworks which on one hand make code a little bit more structured, but on the other do not require client side rendering?

Maybe (stimulus)[https://github.com/stimulusjs/stimulus]? It's what RoR uses IIRC.

**Comment by cxong** [comment]
I'm against server-side rendering logic because we'll need a webserver; plain HTML or client-side rendering are better options.
I think client-side rendering is better and will become better as the site grows.
Currently there are so many games that the page HTML takes the most time and size to load:
![image](https://user-images.githubusercontent.com/1083215/54498938-ea69c880-4960-11e9-879f-762bd389ea6b.png)
Most of that size is HTML tags. The raw data (YAML) is a fraction of that size.

Front end frameworks can also be big, but it's not as bad - they can be cached, and we could also pick a lightweight one like vue or preact: https://gist.github.com/Restuta/cda69e50a853aa64912d

**Comment by piranha** [comment]
The thing is that client-side rendering will be never as fast as static HTML. 123 kb of html is a little! I wonder why it loads for 2 seconds, maybe it's a problem with web server? I'll look into it.

Disclosure: I'm working on JS apps since 2011, and for the last few years I'm at https://kasta.ua - you can check it out, it's pretty fast, but I'll be damned if OSGC isn't a magnitude faster! :)

**Comment by killthekitten** [comment]
I'd also like to sort by number of :octocat: ⭐️ but that would require some db backend to effectively cache the numbers.

**Comment by CommonLoon102** [comment]
Client side rendering is a very bad idea because it only works with JavaScript turned on. This site shouldn't require JS to check basic things, this site is basically a static list. Only web applications should require JS. Everything else should work without JS.

**Comment by piranha** [comment]
@CommonLoon102 well there is no way you can sort something without JS (or adding server, but that sounds even more atrocious).

**Comment by CommonLoon102** [comment]
It would be possible to generate 2 HTMLs based on the YAML, one is sorted by name, the other by updated. There could be a link on both pages to switch to the other.
